# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 428cb44f0b2033fea3f633abf0857d3ae03c593d4a02f1149719e4a9ab3354f240cf15d30ebbe532b33d2676b56519f9d44d93fd7a926f62e4eb5e6bc4bc84bd

test:
  secret_key_base: aa0fb714f3d53b716d314b0227195a9dc1c5c3c468208ceb026420832d85ab909a5cc635d64f6a7b385933dd1623f8b7137002e9e789d5c14ddf6f3b6357c971

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
